language : android
sudo : required
jdk : oraclejdk8
env:
  global :
    - ANROID_API_LEVEL = "28"
    - ANDROID_BUILD_TOOLS_VERSION = "28.0.0"
android:
 components:
 - tools
 - platform-tools
 - build-tools-$ANDROID_BUILD_TOOLS_VERSION
 - android-$ANROID_API_LEVEL
 - extra-google-m2repository
 - extra-android-m2repository # for design library
 - addon-google_apis-google-28 # google play services
 licenses:
 - android-sdk-preview-license-.+
 - android-sdk-license-.+
 - google-sdk-license-.+
before_cache:
   - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
   - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
before_script:
   - chmod +x gradlew
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
script :
    - ./gradlew build --stacktrace
